//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bska.Client.UI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class APPSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static APPSettings defaultInstance = ((APPSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new APPSettings())));
        
        public static APPSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3300000")]
        public decimal MStuffPrice {
            get {
                return ((decimal)(this["MStuffPrice"]));
            }
            set {
                this["MStuffPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1001")]
        public int BookType {
            get {
                return ((int)(this["BookType"]));
            }
            set {
                this["BookType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2001")]
        public int AccidentProccedingConfirm {
            get {
                return ((int)(this["AccidentProccedingConfirm"]));
            }
            set {
                this["AccidentProccedingConfirm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transdata.mdb")]
        public string AccessExportFilePath {
            get {
                return ((string)(this["AccessExportFilePath"]));
            }
            set {
                this["AccessExportFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("701")]
        public int OldSystemFloorType {
            get {
                return ((int)(this["OldSystemFloorType"]));
            }
            set {
                this["OldSystemFloorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Config")]
        public string ConfigUserName {
            get {
                return ((string)(this["ConfigUserName"]));
            }
            set {
                this["ConfigUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EAAAAFR85a1TAcE+C8fOcFSFH3MQ8OVBYu9fFdq95xcHQrpc")]
        public string ConfigPass {
            get {
                return ((string)(this["ConfigPass"]));
            }
            set {
                this["ConfigPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnabledNBookStore {
            get {
                return ((bool)(this["EnabledNBookStore"]));
            }
            set {
                this["EnabledNBookStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnabledStuffDeprication {
            get {
                return ((bool)(this["EnabledStuffDeprication"]));
            }
            set {
                this["EnabledStuffDeprication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackupFolder {
            get {
                return ((string)(this["BackupFolder"]));
            }
            set {
                this["BackupFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogPath {
            get {
                return ((string)(this["LogPath"]));
            }
            set {
                this["LogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string employeeCer {
            get {
                return ((string)(this["employeeCer"]));
            }
            set {
                this["employeeCer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsCompletedAssets {
            get {
                return ((bool)(this["IsCompletedAssets"]));
            }
            set {
                this["IsCompletedAssets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DbServers {
            get {
                return ((string)(this["DbServers"]));
            }
            set {
                this["DbServers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220000000")]
        public decimal CostForOrderMonaghese {
            get {
                return ((decimal)(this["CostForOrderMonaghese"]));
            }
            set {
                this["CostForOrderMonaghese"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ModirConfirmForDisplacementPersonOrder {
            get {
                return ((bool)(this["ModirConfirmForDisplacementPersonOrder"]));
            }
            set {
                this["ModirConfirmForDisplacementPersonOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int SearchDateMonth {
            get {
                return ((int)(this["SearchDateMonth"]));
            }
            set {
                this["SearchDateMonth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CurrentTheme {
            get {
                return ((int)(this["CurrentTheme"]));
            }
            set {
                this["CurrentTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OrderNotify {
            get {
                return ((bool)(this["OrderNotify"]));
            }
            set {
                this["OrderNotify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsClosedMenu {
            get {
                return ((bool)(this["IsClosedMenu"]));
            }
            set {
                this["IsClosedMenu"] = value;
            }
        }
    }
}
