//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bska.Client.UI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class ErrorMessages : global::System.Configuration.ApplicationSettingsBase {
        
        private static ErrorMessages defaultInstance = ((ErrorMessages)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ErrorMessages())));
        
        public static ErrorMessages Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("خطا در برقراری ارتباط با پایگاه داده")]
        public string NoConnection {
            get {
                return ((string)(this["NoConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("خطای ناشناخته.")]
        public string UnhandledException {
            get {
                return ((string)(this["UnhandledException"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("تغییرات با موفقیت ذخیره شد")]
        public string SuccessfullyMessage {
            get {
                return ((string)(this["SuccessfullyMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("نام کاربری وارد نشده است.")]
        public string UserNameEmpty {
            get {
                return ((string)(this["UserNameEmpty"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("هیچ سطری انتخاب نشده است")]
        public string NoRowSelected {
            get {
                return ((string)(this["NoRowSelected"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("آیا شما مطمئن به حذف این آیتم می باشید")]
        public string ConfirmDelete {
            get {
                return ((string)(this["ConfirmDelete"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("سیستم قادر به اتصال به سیستم مکزی نمی باشد")]
        public string NoInternetAccess {
            get {
                return ((string)(this["NoInternetAccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("لطفا ورودی های خود را کنترل کنید")]
        public string InputInvalid {
            get {
                return ((string)(this["InputInvalid"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("آیا مطمئن به ثبت این اطلاعات می باشید")]
        public string AskConfrimation {
            get {
                return ((string)(this["AskConfrimation"]));
            }
        }
    }
}
