//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bska.Client.UI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class HelpPageingAddress : global::System.Configuration.ApplicationSettingsBase {
        
        private static HelpPageingAddress defaultInstance = ((HelpPageingAddress)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HelpPageingAddress())));
        
        public static HelpPageingAddress Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bskaHelp.pdf")]
        public string HelpFileName {
            get {
                return ((string)(this["HelpFileName"]));
            }
            set {
                this["HelpFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BaseInformation/getstuffs")]
        public string StuffApiLink {
            get {
                return ((string)(this["StuffApiLink"]));
            }
            set {
                this["StuffApiLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BaseInformation/getunit")]
        public string UnitApiLink {
            get {
                return ((string)(this["UnitApiLink"]));
            }
            set {
                this["UnitApiLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BaseInformation/GetCompany")]
        public string CountryApiLink {
            get {
                return ((string)(this["CountryApiLink"]));
            }
            set {
                this["CountryApiLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BaseInformation/GetCountry")]
        public string CompanyApiLink {
            get {
                return ((string)(this["CompanyApiLink"]));
            }
            set {
                this["CompanyApiLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BaseInformation/GetInsurance")]
        public string InsuranceApiLink {
            get {
                return ((string)(this["InsuranceApiLink"]));
            }
            set {
                this["InsuranceApiLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BaseInformation/GetCarDetails")]
        public string CarDetailsApiLink {
            get {
                return ((string)(this["CarDetailsApiLink"]));
            }
            set {
                this["CarDetailsApiLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BaseInformation/GetOrganization")]
        public string OrganizationApiLink {
            get {
                return ((string)(this["OrganizationApiLink"]));
            }
            set {
                this["OrganizationApiLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BaseInformation/EstateOrgan")]
        public string EstateOrganApiLink {
            get {
                return ((string)(this["EstateOrganApiLink"]));
            }
            set {
                this["EstateOrganApiLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BaseInformation/Provinces")]
        public string ProvinceApiLink {
            get {
                return ((string)(this["ProvinceApiLink"]));
            }
            set {
                this["ProvinceApiLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BaseInformation/TownShips")]
        public string TownShipsApiLink {
            get {
                return ((string)(this["TownShipsApiLink"]));
            }
            set {
                this["TownShipsApiLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BaseInformation/Zones")]
        public string ZonesApiLink {
            get {
                return ((string)(this["ZonesApiLink"]));
            }
            set {
                this["ZonesApiLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BaseInformation/Cities")]
        public string CitiesApiLink {
            get {
                return ((string)(this["CitiesApiLink"]));
            }
            set {
                this["CitiesApiLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EmployeeIdentity")]
        public string EmployeeIdentityLink {
            get {
                return ((string)(this["EmployeeIdentityLink"]));
            }
            set {
                this["EmployeeIdentityLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BaseInformation/AccountCodings")]
        public string AccountCodingLink {
            get {
                return ((string)(this["AccountCodingLink"]));
            }
            set {
                this["AccountCodingLink"] = value;
            }
        }
    }
}
